apiVersion: v1
kind: Service
metadata:
  name: passguard
  namespace: passguard
  labels:
    app: passguard
spec:
  type: ClusterIP
  selector:
    app: passguard
  ports:
    - name: http
      port: 80
      targetPort: http
